# Generated by Django 3.2.12 on 2022-05-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
