# Generated by Django 3.2.12 on 2022-05-20 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220519_1511'),
        ('movies', '0002_auto_20220520_0023'),
    ]

    operations = [
    ]
